apiVersion: batch/v1
kind: CronJob
metadata:
  name: minute-backup
  namespace: nginx
spec:
  schedule: "*/1 * * * *" # every minute
  jobTemplate:
    spec:
      template:
        metadata:
          name: minute-backup
          labels:
            app: ngnix
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup-container
              image: busybox:latest
              command:
                - sh                     # Use shell
                - -c                     # Execute command string
                - >
                  echo "backup started" &&
                  mkdir -p /backups &&
                  mkdir -p /demo-data &&
                  cp -r /demo-data/* /backups &&
                  echo "backup completed"
              volumeMounts:
                - name: data-volume
                  mountPath: /demo-data
                - name: backup-volume
                  mountPath: /backups
          volumes:
            - name: data-volume
              emptyDir: {}
            - name: backup-volume
              hostPath:
                path: /backups
                type: DirectoryOrCreate
