#create one time job in nginx namespace
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task
    spec:
      restartPolicy: Never
      containers:
        - name: batch-container
          image: busybox:latest
          command:
            - sh
            - -c
            - echo "Hello from the Kubernetes cluster" && sleep 10
